AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for queue-up

Globals:
  Function:
    Timeout: 5

Resources:
  QueueUpFunction:
    Type: AWS::Serverless::Function
    DependsOn: ModelUpdatesSQSQueue
    Properties:
      CodeUri: bin/
      Handler: queue-up
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Environment:
        Variables:
          SQS_URL: !Ref ModelUpdatesSQSQueue
      Policies:
      - AWSLambdaExecute # Managed Policy
      - Version: '2012-10-17' # Policy Document
        Statement:
          - Effect: Allow
            Action:
              - sqs:SendMessage
            Resource:
              Fn::GetAtt:
                - ModelUpdatesSQSQueue
                - Arn
      Events:
        PutObject:
          Type: S3
          Properties:
            Bucket: !Ref SrcS3Bucket
            Events: s3:ObjectCreated:*

  SrcS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: sample-models-bucket
      LifecycleConfiguration:
        Rules:
        - ExpirationInDays: 7
          Status: Enabled

  ModelUpdatesSQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      FifoQueue: 'true'
      ContentBasedDeduplication: 'true'
      MessageRetentionPeriod: 1209600
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
          - ModelUpdatesSQSDeadLetterQueue
          - Arn
        maxReceiveCount: 3

  ModelUpdatesSQSDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      FifoQueue: 'true'
      ContentBasedDeduplication: 'true'
      MessageRetentionPeriod: 1209600

Outputs:
  QueueUpFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt QueueUpFunction.Arn
  QueueUpFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt QueueUpFunctionRole.Arn
  QueueARN:
    Description: ARN of SQS Queue
    Value:
      Fn::GetAtt:
      - ModelUpdatesSQSQueue
      - Arn
  QueueURL:
    Description: URL of SQS Queue
    Value:
      Ref: ModelUpdatesSQSQueue